#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CASK_PATH="${ROOT_DIR}/Casks/localshot.rb"

usage() {
  cat <<'USAGE'
Usage: scripts/update-homebrew-cask.sh TAG SHA256_OR_FILE

Updates Casks/localshot.rb for a GitHub release tag such as v1.20.1. The second
argument may be a raw SHA-256 value or a .sha256 file generated by shasum.
USAGE
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]
then
  usage
  exit 0
fi

[[ $# -eq 2 ]] || {
  usage >&2
  exit 64
}

tag="$1"
checksum_source="$2"

[[ "${tag}" =~ ^v[0-9]+[.][0-9]+[.][0-9]+([-.][A-Za-z0-9.]+)?$ ]] ||
  die "tag must look like v1.20.1"

if [[ -f "${checksum_source}" ]]
then
  sha256="$(awk '{print $1; exit}' "${checksum_source}")"
else
  sha256="${checksum_source}"
fi

[[ "${sha256}" =~ ^[0-9a-f]{64}$ ]] ||
  die "checksum must be a lowercase SHA-256 value"

version="${tag#v}"

[[ -f "${CASK_PATH}" ]] || die "missing ${CASK_PATH}"

perl -0pi -e "s/^\s*version \"[^\"]+\"/  version \"${version}\"/m; s/^\s*sha256 \"[0-9a-f]{64}\"/  sha256 \"${sha256}\"/m" "${CASK_PATH}"

"${ROOT_DIR}/scripts/check-homebrew-cask.sh"
